FROM node:20.12.0

# Time Zone
ENV TZ Asia/Tokyo

# Language
ENV LANG ja_JP.UTF-8
ENV LANGUAGE ja_JP:ja
ENV LC_ALL ja_JP.UTF-8


WORKDIR /app

COPY package*.json ./

# @vue/cliをグローバルにインストール
RUN npm install -g @vue/cli  

RUN npm install

COPY . .

EXPOSE 8080

CMD ["npm", "run", "serve"]